#include QMK_KEYBOARD_H
// qmk flash -kb mango_dactyl -km hanmangokiw
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

	[0] = LAYOUT_mirror(
		TO(3), KC_1, KC_2, KC_3, KC_4, KC_5, KC_MINUS,
		KC_BACKSLASH, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_LEFT_BRACKET,
		TO(1), KC_A, KC_S, KC_D, KC_F, KC_G, KC_GRAVE,
		TO(2), KC_Z, KC_X, KC_C, KC_V, KC_B,
		MO(4), KC_LEFT_GUI, LM(4, MOD_LALT), KC_TAB, KC_LEFT_SHIFT, KC_SPACE, KC_BACKSPACE, KC_ESC,
														KC_LEFT_CTRL, KC_DELETE,

			KC_VOLU, KC_6, KC_7, KC_8, KC_9, KC_0, TO(2),
			KC_VOLD, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BACKSLASH,
			KC_QUOTE, KC_H, KC_J, KC_K, KC_L, KC_SEMICOLON, PB_29,
			KC_N, KC_M, KC_COMMA, KC_DOT, KC_SLASH, TO(1),
		KC_MINUS, KC_EQUAL, KC_BACKSPACE, KC_ENTER, KC_MPRV, KC_MPLY, KC_MNXT, TO(3),
		KC_LEFT_BRACKET, KC_RIGHT_BRACKET
		),

	[1] = LAYOUT_mirror(
		TO(3), KC_6, KC_7, KC_8, KC_9, KC_0, KC_EQUAL,
		KC_TRNS, KC_P, KC_O, KC_I, KC_U, KC_Y, KC_RIGHT_BRACKET,
		TO(0), KC_SEMICOLON, KC_L, KC_K, KC_J, KC_H, KC_QUOTE,
		TO(2), KC_SLASH, KC_DOT, KC_COMMA, KC_M, KC_N,
		PB_28, KC_TRNS, LM(5, MOD_LALT), PB_30, KC_TRNS, PB_31, PB_31, PB_31,
														KC_TRNS, PB_31,
														
			KC_TRNS, KC_NO, KC_NO, KC_MINS, KC_EQL, KC_NO, TO(2),
			KC_TRNS, KC_PAGE_UP, KC_LEFT_BRACKET, KC_UP, KC_RIGHT_BRACKET, KC_NO, KC_RIGHT_ALT,
			KC_NO, KC_PAGE_DOWN, KC_LEFT, KC_DOWN, KC_RIGHT, KC_NO, KC_TRNS,
			KC_NO, KC_NO, KC_HOME, KC_END, KC_NO, TO(0),
		KC_TRNS, KC_TRNS, PB_31, PB_31, KC_TRNS, KC_TRNS, KC_TRNS, TO(3),
		KC_TRNS, KC_TRNS
		),

	[2] = LAYOUT_mirror(
		TO(3), KC_NO, KC_MINS, KC_EQL, KC_NO, KC_NO, KC_NO,
		KC_TRNS, KC_NO, KC_LEFT_BRACKET, KC_UP, KC_RIGHT_BRACKET, KC_PAGE_UP, KC_NO,
		TO(1), KC_NO, KC_LEFT, KC_DOWN, KC_RIGHT, KC_PAGE_DOWN, KC_NO,
		TO(0), KC_NO, KC_HOME, KC_END, KC_NO, KC_NO,
		PB_28, KC_TRNS, KC_TRNS, PB_30, KC_TRNS, PB_31, PB_31, PB_31,
														KC_TRNS, PB_31,
														
			KC_TRNS, QK_BOOT, KC_NO, KC_MS_BTN3, KC_NO, KC_NO, TO(0),
			KC_TRNS, KC_MS_WH_UP, KC_MS_BTN1, KC_MS_UP, KC_MS_BTN2, KC_NO, KC_TRNS,
			KC_NO, KC_MS_WH_DOWN, KC_MS_LEFT, KC_MS_DOWN, KC_MS_RIGHT, KC_NO, KC_TRNS,
			KC_NO, KC_NO, KC_WWW_FORWARD, KC_WWW_BACK, KC_NO, TO(1),
		KC_TRNS, KC_TRNS, PB_31, PB_31, KC_TRNS, KC_TRNS, KC_TRNS, TO(3),
		KC_TRNS, KC_TRNS
		),

	[3] = LAYOUT_mirror(
		TO(0), KC_NO, KC_NO, KC_MS_BTN3, KC_NO, QK_BOOT, KC_NO,
		KC_TRNS, KC_NO, KC_MS_BTN1, KC_MS_UP, KC_MS_BTN2, KC_MS_WH_UP, KC_NO,
		TO(1), KC_NO, KC_MS_LEFT, KC_MS_DOWN, KC_MS_RIGHT, KC_MS_WH_DOWN, KC_NO,
		TO(2), KC_NO, KC_WWW_BACK, KC_WWW_FORWARD, KC_MS_WH_LEFT, KC_MS_WH_RIGHT,
		PB_28, KC_TRNS, KC_TRNS, PB_30, KC_TRNS, PB_31, PB_31, PB_31,
														KC_TRNS, PB_31,
														
			KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(2),
			KC_TRNS, KC_NO, KC_KP_7, KC_KP_8, KC_KP_9, KC_NO, KC_TRNS,
			KC_NO, KC_NO, KC_KP_4, KC_KP_5, KC_KP_6, KC_NO, KC_TRNS,
				   KC_NO, KC_KP_1, KC_KP_2, KC_KP_3, KC_NO, TO(1),
		KC_TRNS, KC_TRNS, PB_31, PB_31, KC_KP_0, KC_PDOT, KC_NUM_LOCK, TO(0),
		KC_TRNS, KC_TRNS
		),

	[4] = LAYOUT_mirror(
		KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F11,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TAB, KC_TRNS, PB_31, PB_31, PB_31,
														KC_TRNS, PB_31,

		KC_F12, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
														KC_TRNS, KC_TRNS
		),

	[5] = LAYOUT_mirror(
		KC_F12, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TAB, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
														KC_TRNS, KC_TRNS,

		KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F11,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
														KC_TRNS, KC_TRNS
		),





	[6] = LAYOUT_rev(
		TO(9), KC_1, KC_2, KC_3, KC_4, KC_5, KC_MINUS,
		KC_BACKSLASH, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_LEFT_BRACKET,
		TO(7), KC_A, KC_S, KC_D, KC_F, KC_G, KC_GRAVE,
		TO(8), KC_Z, KC_X, KC_C, KC_V, KC_B,
		MO(10), KC_LEFT_GUI, LM(10, MOD_LALT), KC_TAB, KC_LEFT_SHIFT, KC_SPACE, KC_BACKSPACE, KC_ESC,
														KC_LEFT_CTRL, KC_DELETE,

			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
		PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
		PB_32, PB_32
		),

	[7] = LAYOUT_rev(
		TO(9), KC_6, KC_7, KC_8, KC_9, KC_0, KC_EQUAL,
		KC_TRNS, KC_P, KC_O, KC_I, KC_U, KC_Y, KC_RIGHT_BRACKET,
		TO(6), KC_SEMICOLON, KC_L, KC_K, KC_J, KC_H, KC_QUOTE,
		TO(8), KC_SLASH, KC_DOT, KC_COMMA, KC_M, KC_N,
		PB_27, KC_TRNS, LM(11, MOD_LALT), PB_30, KC_TRNS, PB_31, PB_31, PB_31,
														KC_TRNS, PB_31,

			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
		PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
		PB_32, PB_32
		),

	[8] = LAYOUT_rev(
		TO(9), KC_NO, KC_EQL, KC_MINS, KC_NO, KC_NO, KC_NO,
		KC_TRNS, KC_BACKSLASH, KC_RIGHT_BRACKET, KC_UP, KC_LEFT_BRACKET, KC_PAGE_UP, KC_NO,
		TO(7), KC_NO, KC_RIGHT, KC_DOWN, KC_LEFT, KC_PAGE_DOWN, KC_NO,
		TO(6), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		PB_27, KC_TRNS, KC_TRNS, PB_30, KC_TRNS, PB_31, PB_31, PB_31,
														KC_TRNS, PB_31,

			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
		PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
		PB_32, PB_32
		),

	[9] = LAYOUT_rev(
		TO(6), KC_NO, KC_NO, KC_MS_BTN3, KC_NO, QK_BOOT, KC_NO,
		KC_TRNS, KC_NO, KC_MS_BTN2, KC_MS_UP, KC_MS_BTN1, KC_MS_WH_UP, KC_NO,
		TO(7), KC_NO, KC_MS_RIGHT, KC_MS_DOWN, KC_MS_LEFT, KC_MS_WH_DOWN, KC_NO,
		TO(8), KC_NO, KC_WWW_BACK, KC_WWW_FORWARD, KC_MS_WH_LEFT, KC_MS_WH_RIGHT,
		PB_27, KC_TRNS, KC_TRNS, PB_30, KC_TRNS, PB_31, PB_31, PB_31,
														KC_TRNS, PB_31,

			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
		PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
		PB_32, PB_32
		),

	[10] = LAYOUT_rev(
		KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F11,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TAB, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
														KC_TRNS, KC_TRNS,

			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
		PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
		PB_32, PB_32
		),

	[11] = LAYOUT_rev(
		KC_F12, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TAB, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
														KC_TRNS, KC_TRNS,

			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
			PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
		PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32, PB_32,
		PB_32, PB_32
		),
};
